### ΛRGVUS Advanced Firewall for Arch Linux
### Interface WAN (Internet connection). E.g: enp0s3, eno1
### Note: required only when MASQUERADE_ENABLE="y"
	INTERFACE_WAN=""

### Internal Network (if any). E.g: enp0s8
	INTERFACE_LAN=""

### Masquerade network. Option: n|y
	MASQUERADE_ENABLE="n"

### Protection levels
	PROTECTION_LEVEL="high"  # low|medium|high|paranoid

### SSH configuration allowed clients (comma separated)
	### CAUTION: If "ALLOW_SSH" but "SSH_CLIENTS_IP" is empty, SSH will be allowed
	### from anywhere. If you want to allow SSH for a specific IP or network, use "SSH_CLIENTS_IP".
	ALLOW_SSH="n"
	# Example: SSH_CLIENTS_IP="192.168.0.2/32,192.168.1.0/24"
	SSH_CLIENTS_IP=""
	# Tip: It is recommended to change SSH to a high port, for example: 2222
	SSH_PORT="22"

### Samba configuration
	### CAUTION: If "ALLOW_SAMBA" but "SAMBA_CLIENTS_IP" is empty, SAMBA will be allowed
	### from anywhere. If you want to allow SAMBA for a specific IP or network, use "SAMBA_CLIENTS_IP".
	ALLOW_SAMBA="n"
	# Example: SAMBA_CLIENTS_IP="192.168.0.2/32,192.168.1.0/24"
	SAMBA_CLIENTS_IP=""

### Services to allow
	ALLOW_ICMP="y"

### UDP ports to open (comma separated). E.g: 53,443 (QUIC/HTTP3)
	OPEN_PORTS_UDP=""

### Advanced protection
	SYN_FLOOD_PROTECTION="y"
	DDOS_PROTECTION="y"
	PORT_SCAN_PROTECTION="y"
	ANTI_SPOOFING="y"